<?php
/**
 * Event
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

/**
 * Event
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Event
{
    
    /** @var \DateTime $timestamp */
    private $timestamp;
    
    /** @var string $user */
    private $user;
    
    /** @var string $event */
    private $event;
    
    /** @var string $objectId */
    private $objectId;
    
    /** @var object $data */
    private $data;
}
