<?php
/**
 * Insight
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

/**
 * Insight
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Insight
{
    
    /** @var string $id */
    private $id;
    
    /** @var \OpenAPIServer\Model\InsightLinks[] $links */
    private $links;
    
    /** @var string $insight */
    private $insight;
    
    /** @var int $votes */
    private $votes;
}
