<?php
/**
 * SnapshotVariation
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

/**
 * SnapshotVariation
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class SnapshotVariation
{
    
    /** @var int $variation */
    private $variation;
    
    /** @var int $samples */
    private $samples;
    
    /** @var int $requiredSamples */
    private $requiredSamples;
    
    /** @var \OpenAPIServer\Model\SnapshotVariationData $data */
    private $data;
}
