<?php
/**
 * SnapshotVariationData
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

/**
 * SnapshotVariationData
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class SnapshotVariationData
{
    
    /** @var float $value */
    private $value;
    
    /** @var object $rawData */
    private $rawData;
    
    /** @var bool $enoughData */
    private $enoughData;
    
    /** @var float $confidenceLow */
    private $confidenceLow;
    
    /** @var float $confidenceHigh */
    private $confidenceHigh;
}
