<?php
/**
 * SnapshotMetrics
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

/**
 * SnapshotMetrics
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class SnapshotMetrics
{
    
    /** @var \OpenAPIServer\Model\Metric $metric */
    private $metric;
    
    /** @var \OpenAPIServer\Model\SnapshotVariation[] $variations */
    private $variations;
}
