<?php
/**
 * Snapshot
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

/**
 * Snapshot
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Snapshot
{
    
    /** @var string $id */
    private $id;
    
    /** @var string $testId */
    private $testId;
    
    /** @var \DateTime $created */
    private $created;
    
    /** @var \OpenAPIServer\Model\SnapshotMetrics[] $metrics */
    private $metrics;
}
