<?php
/**
 * TestResults
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

/**
 * TestResults
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class TestResults
{
    
    /** @var string $summary */
    private $summary;
    
    /** @var string $analysis */
    private $analysis;
    
    /** @var string $outcome */
    private $outcome;
    
    /** @var string $futureBaseline */
    private $futureBaseline;
}
