<?php
/**
 * TestSummary
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

/**
 * TestSummary
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class TestSummary
{
    
    /** @var string $id */
    private $id;
    
    /** @var string $name */
    private $name;
    
    /** @var \OpenAPIServer\Model\TestStatus $status */
    private $status;
    
    /** @var string $description */
    private $description;
    
    /** @var string $hypothesis */
    private $hypothesis;
    
    /** @var \OpenAPIServer\Model\TestSummaryVariations[] $variations */
    private $variations;
    
    /** @var string $outcome */
    private $outcome;
    
    /** @var \DateTime $createdAt */
    private $createdAt;
    
    /** @var \DateTime $updatedAt */
    private $updatedAt;
    
    /** @var \DateTime $startedAt */
    private $startedAt;
    
    /** @var \DateTime $stoppedAt */
    private $stoppedAt;
}
