<?php
/**
 * Variation
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

/**
 * Variation
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Variation
{
    
    /** @var int $variation */
    private $variation;
    
    /** @var string $name */
    private $name;
    
    /** @var float $weight */
    private $weight;
    
    /** @var bool $active */
    private $active;
    
    /** @var \OpenAPIServer\Model\VariationImages[] $images */
    private $images;
}
