<?php
/**
 * InsightsApiTest
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * AB Crusher API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\InsightsApi;

/**
 * InsightsApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\InsightsApi
 */
class InsightsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createInsight
     *
     * Create a new Insight.
     *
     * @covers ::createInsight
     */
    public function testCreateInsight()
    {
    }

    /**
     * Test case for deleteInsight
     *
     * Delete a Insight.
     *
     * @covers ::deleteInsight
     */
    public function testDeleteInsight()
    {
    }

    /**
     * Test case for getInsight
     *
     * Return data for a single Insight.
     *
     * @covers ::getInsight
     */
    public function testGetInsight()
    {
    }

    /**
     * Test case for getInsights
     *
     * Returns a list of insights.
     *
     * @covers ::getInsights
     */
    public function testGetInsights()
    {
    }

    /**
     * Test case for updateInsight
     *
     * Update a Insight.
     *
     * @covers ::updateInsight
     */
    public function testUpdateInsight()
    {
    }
}
