<?php
/**
 * TestsApiTest
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * AB Crusher API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\TestsApi;

/**
 * TestsApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\TestsApi
 */
class TestsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createSnapshot
     *
     * Create a new snapshot for a test.
     *
     * @covers ::createSnapshot
     */
    public function testCreateSnapshot()
    {
    }

    /**
     * Test case for createTest
     *
     * Create a new Test.
     *
     * @covers ::createTest
     */
    public function testCreateTest()
    {
    }

    /**
     * Test case for deleteTest
     *
     * Delete a Test.
     *
     * @covers ::deleteTest
     */
    public function testDeleteTest()
    {
    }

    /**
     * Test case for getSnapshots
     *
     * Return data snapshots for a test.
     *
     * @covers ::getSnapshots
     */
    public function testGetSnapshots()
    {
    }

    /**
     * Test case for getTest
     *
     * Return data for a single Test.
     *
     * @covers ::getTest
     */
    public function testGetTest()
    {
    }

    /**
     * Test case for getTests
     *
     * Returns a list of current and past tests.
     *
     * @covers ::getTests
     */
    public function testGetTests()
    {
    }

    /**
     * Test case for updateTest
     *
     * Update a Test.
     *
     * @covers ::updateTest
     */
    public function testUpdateTest()
    {
    }

    /**
     * Test case for uploadScreenshot
     *
     * Upload a screenshot of a test variation.
     *
     * @covers ::uploadScreenshot
     */
    public function testUploadScreenshot()
    {
    }
}
