<?php
/**
 * SnapshotVariationDataTest
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * AB Crusher API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\SnapshotVariationData;

/**
 * SnapshotVariationDataTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\SnapshotVariationData
 */
class SnapshotVariationDataTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SnapshotVariationData"
     */
    public function testSnapshotVariationData()
    {
        $testSnapshotVariationData = new SnapshotVariationData();
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
    }

    /**
     * Test attribute "rawData"
     */
    public function testPropertyRawData()
    {
    }

    /**
     * Test attribute "enoughData"
     */
    public function testPropertyEnoughData()
    {
    }

    /**
     * Test attribute "confidenceLow"
     */
    public function testPropertyConfidenceLow()
    {
    }

    /**
     * Test attribute "confidenceHigh"
     */
    public function testPropertyConfidenceHigh()
    {
    }
}
