<?php
/**
 * SlimRouter
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * AB Crusher API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */
namespace OpenAPIServer;

use Slim\Factory\AppFactory;
use Slim\Interfaces\RouteInterface;
use Psr\Container\ContainerInterface;
use InvalidArgumentException;
use Dyorg\TokenAuthentication;
use Dyorg\TokenAuthentication\TokenSearch;
use Psr\Http\Message\ServerRequestInterface;
use OpenAPIServer\Middleware\JsonBodyParserMiddleware;
use Exception;

/**
 * SlimRouter Class Doc Comment
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class SlimRouter
{

    /** @var App instance */
    private $slimApp;

    /** @var array[] list of all api operations */
    private $operations = [
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '/api/v1',
            'path' => '/events',
            'apiPackage' => 'OpenAPIServer\Api',
            'classname' => 'AbstractEventsApi',
            'userClassname' => 'EventsApi',
            'operationId' => 'getEvents',
            'authMethods' => [
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '/api/v1',
            'path' => '/event/{eventId}',
            'apiPackage' => 'OpenAPIServer\Api',
            'classname' => 'AbstractEventsApi',
            'userClassname' => 'EventsApi',
            'operationId' => 'getEvent',
            'authMethods' => [
            ],
        ],
        [
            'httpMethod' => 'POST',
            'basePathWithoutHost' => '/api/v1',
            'path' => '/insights',
            'apiPackage' => 'OpenAPIServer\Api',
            'classname' => 'AbstractInsightsApi',
            'userClassname' => 'InsightsApi',
            'operationId' => 'createInsight',
            'authMethods' => [
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '/api/v1',
            'path' => '/insights',
            'apiPackage' => 'OpenAPIServer\Api',
            'classname' => 'AbstractInsightsApi',
            'userClassname' => 'InsightsApi',
            'operationId' => 'getInsights',
            'authMethods' => [
            ],
        ],
        [
            'httpMethod' => 'DELETE',
            'basePathWithoutHost' => '/api/v1',
            'path' => '/insight/{insightId}',
            'apiPackage' => 'OpenAPIServer\Api',
            'classname' => 'AbstractInsightsApi',
            'userClassname' => 'InsightsApi',
            'operationId' => 'deleteInsight',
            'authMethods' => [
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '/api/v1',
            'path' => '/insight/{insightId}',
            'apiPackage' => 'OpenAPIServer\Api',
            'classname' => 'AbstractInsightsApi',
            'userClassname' => 'InsightsApi',
            'operationId' => 'getInsight',
            'authMethods' => [
            ],
        ],
        [
            'httpMethod' => 'PUT',
            'basePathWithoutHost' => '/api/v1',
            'path' => '/insight/{insightId}',
            'apiPackage' => 'OpenAPIServer\Api',
            'classname' => 'AbstractInsightsApi',
            'userClassname' => 'InsightsApi',
            'operationId' => 'updateInsight',
            'authMethods' => [
            ],
        ],
        [
            'httpMethod' => 'POST',
            'basePathWithoutHost' => '/api/v1',
            'path' => '/tests',
            'apiPackage' => 'OpenAPIServer\Api',
            'classname' => 'AbstractTestsApi',
            'userClassname' => 'TestsApi',
            'operationId' => 'createTest',
            'authMethods' => [
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '/api/v1',
            'path' => '/tests',
            'apiPackage' => 'OpenAPIServer\Api',
            'classname' => 'AbstractTestsApi',
            'userClassname' => 'TestsApi',
            'operationId' => 'getTests',
            'authMethods' => [
            ],
        ],
        [
            'httpMethod' => 'POST',
            'basePathWithoutHost' => '/api/v1',
            'path' => '/test/{testId}/snapshots',
            'apiPackage' => 'OpenAPIServer\Api',
            'classname' => 'AbstractTestsApi',
            'userClassname' => 'TestsApi',
            'operationId' => 'createSnapshot',
            'authMethods' => [
            ],
        ],
        [
            'httpMethod' => 'DELETE',
            'basePathWithoutHost' => '/api/v1',
            'path' => '/test/{testId}',
            'apiPackage' => 'OpenAPIServer\Api',
            'classname' => 'AbstractTestsApi',
            'userClassname' => 'TestsApi',
            'operationId' => 'deleteTest',
            'authMethods' => [
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '/api/v1',
            'path' => '/test/{testId}/snapshots',
            'apiPackage' => 'OpenAPIServer\Api',
            'classname' => 'AbstractTestsApi',
            'userClassname' => 'TestsApi',
            'operationId' => 'getSnapshots',
            'authMethods' => [
            ],
        ],
        [
            'httpMethod' => 'GET',
            'basePathWithoutHost' => '/api/v1',
            'path' => '/test/{testId}',
            'apiPackage' => 'OpenAPIServer\Api',
            'classname' => 'AbstractTestsApi',
            'userClassname' => 'TestsApi',
            'operationId' => 'getTest',
            'authMethods' => [
            ],
        ],
        [
            'httpMethod' => 'PUT',
            'basePathWithoutHost' => '/api/v1',
            'path' => '/test/{testId}',
            'apiPackage' => 'OpenAPIServer\Api',
            'classname' => 'AbstractTestsApi',
            'userClassname' => 'TestsApi',
            'operationId' => 'updateTest',
            'authMethods' => [
            ],
        ],
        [
            'httpMethod' => 'POST',
            'basePathWithoutHost' => '/api/v1',
            'path' => '/test/{testId}/{variation}/screenshot',
            'apiPackage' => 'OpenAPIServer\Api',
            'classname' => 'AbstractTestsApi',
            'userClassname' => 'TestsApi',
            'operationId' => 'uploadScreenshot',
            'authMethods' => [
            ],
        ],
    ];

    /**
     * Class constructor
     *
     * @param ContainerInterface|array $settings Either a ContainerInterface or an associative array of app settings
     *
     * @throws Exception When implementation class doesn't exists
     */
    public function __construct($settings = [])
    {
        if ($settings instanceof ContainerInterface) {
            // Set container to create App with on AppFactory
            AppFactory::setContainer($settings);
        }
        $this->slimApp = AppFactory::create();

        // middlewares requires Psr\Container\ContainerInterface
        $container = $this->slimApp->getContainer();


        $userOptions = null;
        if ($settings instanceof ContainerInterface && $settings->has('tokenAuthenticationOptions')) {
            $userOptions = $settings->get('tokenAuthenticationOptions');
        } elseif (is_array($settings) && isset($settings['tokenAuthenticationOptions'])) {
            $userOptions = $settings['tokenAuthenticationOptions'];
        }

        foreach ($this->operations as $operation) {
            $callback = function ($request, $response, $arguments) use ($operation) {
                $message = "How about extending {$operation['classname']} by {$operation['apiPackage']}\\{$operation['userClassname']} class implementing {$operation['operationId']} as a {$operation['httpMethod']} method?";
                throw new Exception($message);
                $response->getBody()->write($message);
                return $response->withStatus(501);
            };
            $middlewares = [new JsonBodyParserMiddleware()];

            if (class_exists("\\{$operation['apiPackage']}\\{$operation['userClassname']}")) {
                $callback = "\\{$operation['apiPackage']}\\{$operation['userClassname']}:{$operation['operationId']}";
                error_log($operation['httpMethod'].' '."{$operation['basePathWithoutHost']}{$operation['path']}"." => ".$callback);
            }

            $this->addRoute(
                [$operation['httpMethod']],
                "{$operation['basePathWithoutHost']}{$operation['path']}",
                $callback,
                $middlewares
            )->setName($operation['operationId']);
        }
    }

    /**
     * Merges user defined options with dynamic params
     *
     * @param array $staticOptions Required static options
     * @param array $userOptions   User options
     *
     * @return array Merged array
     */
    private function getTokenAuthenticationOptions(array $staticOptions, array $userOptions = null)
    {
        if (is_array($userOptions) === false) {
            return $staticOptions;
        }

        return array_merge($userOptions, $staticOptions);
    }

    /**
     * Add route with multiple methods
     *
     * @param string[]        $methods     Numeric array of HTTP method names
     * @param string          $pattern     The route URI pattern
     * @param callable|string $callable    The route callback routine
     * @param array|null      $middlewares List of middlewares
     *
     * @return RouteInterface
     *
     * @throws InvalidArgumentException If the route pattern isn't a string
     */
    public function addRoute(array $methods, string $pattern, $callable, $middlewares = [])
    {
        $route = $this->slimApp->map($methods, $pattern, $callable);
        foreach ($middlewares as $middleware) {
            $route->add($middleware);
        }
        return $route;
    }

    /**
     * Returns Slim Framework instance
     *
     * @return App
     */
    public function getSlimApp()
    {
        return $this->slimApp;
    }
}
